Basic structure of aplication
PowerLevel9000/LeaderboardWithApi pull request #2
Opened 2023-02-07 17:01 UTC by PowerLevel9000

# it's just a Structure

- it gives you glimpses of what coming in the future

## happy coding
![KtoKounotoriGIF](https://user-images.githubusercontent.com/116451144/217312629-1781bcdc-8a58-4087-9285-c36110b84f19.gif)

2023-02-07 17:28 UTC, julie-ify requested changes
## Hi @PowerLevel9000,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 17:28 UTC, julie-ify commented on README.md
> -- [📝 License](#license)
- [ ] Your readme ended at the "Getting Started" section. Kindly add the remaining links as we have on the template and add their corresponding sections.

  Note that only the FAQ section is optional, the rest are mandatory.

  ![iot](https://user-images.githubusercontent.com/81468675/217319446-467ca5d4-0228-4d46-a3ce-a6db982927ad.jpg)

2023-02-08 02:24 UTC, Reem-lab approved these changes
# Hi @PowerLevel9000,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
- No Linters error ✨✅
- Followed Gitflow ✅
- Great working on the functionality of set up✅
- Professional README ✅




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 02:31 UTC, PowerLevel9000 reviewed
Hi @PowerLevel9000 , 

Your project is complete there is nothing to say except to merge it 

![FatGuyGIF](https://user-images.githubusercontent.com/116451144/217256255-4577afd5-d9cd-4d8a-9ec4-d59f6ca1e1f3.gif)

## Highlights
- Followed Gitflow ✔️
- Great working on the functionality of set up✔️
- Professional README ✔️
- Linters are Green 🟢


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Disclaimer: The code reviewed in this document is solely for the purpose of practicing code review skills and not for production use. The author has made every effort to ensure the accuracy of the code but makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the code or the information, products, services, or related graphics contained in the code for any purpose. Any reliance you place on such information is therefore strictly at your own risk. In no event will the author be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this code.

2023-02-08 02:33 UTC, merged